# Generated by Django 3.2.7 on 2021-09-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('frame_truss_margin', models.CharField(max_length=255)),
                ('discount_group', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('job_name', models.CharField(max_length=255)),
                ('job_company', models.CharField(max_length=255)),
                ('pre_nail_date', models.DateField()),
                ('site_address', models.TextField()),
                ('job_location', models.TextField()),
                ('client', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('logged_date', models.DateField()),
                ('client_address', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('email_skip', models.BooleanField()),
                ('email_arie', models.BooleanField()),
                ('email_luci', models.BooleanField()),
                ('email_vip', models.BooleanField()),
                ('email_jason', models.BooleanField()),
                ('email_to', models.EmailField(max_length=254)),
                ('wind_zone', models.IntegerField(choices=[(0, 'NONE'), (1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH'), (4, 'VERY_HIGH'), (5, 'EXTRA_HIGH')], default=0)),
                ('corrosion_zone', models.IntegerField(choices=[(0, 'ZONE_A_None'), (1, 'ZONE_B_LOW'), (2, 'ZONE_C_MEDIUM'), (3, 'ZONE_D_HIGH')], default=0)),
                ('interior_doors_notes', models.BooleanField()),
                ('door_hardware_notes', models.BooleanField()),
                ('scotia_notes', models.BooleanField()),
                ('skirting_notes', models.BooleanField()),
                ('architraves_notes', models.BooleanField()),
                ('fascia_type_notes', models.BooleanField()),
                ('ceiling_batten_notes', models.BooleanField()),
                ('roof_material_notes', models.BooleanField()),
                ('truss_penetrations_notes', models.BooleanField()),
                ('special_trusses_notes', models.BooleanField()),
                ('alteration_notes', models.TextField()),
                ('plan_file', models.FileField(blank=True, null=True, upload_to='jobs/dog-profiles')),
                ('engineer_plans_file', models.FileField(blank=True, null=True, upload_to='images/dog-profiles')),
                ('window_door_plan_file', models.FileField(blank=True, null=True, upload_to='images/dog-profiles')),
                ('specification_file', models.FileField(blank=True, null=True, upload_to='images/dog-profiles')),
                ('dwg_floor_plan_file', models.FileField(blank=True, null=True, upload_to='images/dog-profiles')),
                ('dimensioned_floor_on_plan', models.CharField(max_length=255)),
                ('elevations_on_plan', models.CharField(max_length=255)),
                ('cross_section_on_plan', models.CharField(max_length=255)),
                ('roof_pitch_on_plan', models.CharField(max_length=255)),
                ('electrical_plan_on_plan', models.CharField(max_length=255)),
                ('rafters_design_and_sizing_on_plan', models.CharField(max_length=255)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.rep')),
                ('suppliers', models.ManyToManyField(to='members.Supplier')),
            ],
        ),
    ]
