# Generated by Django 3.2.7 on 2021-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210908_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/rep/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/supplier/'),
        ),
    ]
